
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'COLORECTAL','INSULIN',1.5,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'PANCREATIC','INSULIN',4.78,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','BENAZEPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','IRBESARTAN',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','VALSARTAN',1.08,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'RENAL-CELL CANCER','BENDROFLUMETHIAZIDE',1.43,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'NON-MELANOMA SKIN CANCER','ETANERCEPT',2.02,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','ETANERCEP',3.29,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'BLADDER','PIOGLITAZONE',1.22,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'BLADDER','ROSIGLITAZONE',1.15,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','CYCLOSPORINE',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','TACROLIMUS',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','SIROLIMUS',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','EVEROLIMUS',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','MYCOPHENOLATE MOFETIL',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','MIZORIBINE',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','LEFLUNOMIDE',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','AZATHIOPRINE',1.58,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','INSULIN',1.39,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','ENALAPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','FOSINOPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','LISINOPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','MOEXIPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','PERINDOPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','QUINAPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','RAMIPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','TRANDOLAPRIL',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','LOSARTAN',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','CANDESARTAN',1.14,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'RENAL-CELL CANCER','HYDROCHLOROTHIAZIDE',1.43,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'RENAL-CELL CANCER','CHLORTALIDONE',1.43,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'RENAL-CELL CANCER','NDAPAMIDE',1.43,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'NON-MELANOMA SKIN CANCER','INFLIXIMAB',2.02,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'NON-MELANOMA SKIN CANCER','ADALIMUMAB',2.02,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'NON-MELANOMA SKIN CANCER','CERTOLIZUMAB PEGOL',2.02,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'NON-MELANOMA SKIN CANCER','GOLIMUMAB',2.02,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','INFLIXIMAB',3.29,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','ADALIMUMAB',3.29,NULL,NULL);
INSERT INTO relative_risk_db(id,"cancer_type","medicine_name","relative_risk","ConfIntervalRR_Lower","ConfIntervalRR_Upper") VALUES (NULL,'ALL','CERTOLIZUMAB PEGOL',3.29,NULL,NULL);
